#!/sbin/sh
rm -rf "/system/app/BasicDreams"
rm -rf "/system/app/BookmarkProvider"
rm -rf "/system/app/Browser2"
rm -rf "/system/app/EasterEgg"
rm -rf "/system/app/Email"
rm -rf "/system/app/LiveWallpapersPicker"
rm -rf "/system/app/Music"
rm -rf "/system/app/PhotoTable"
rm -rf "/system/app/QuickSearchBox"
rm -rf "/system/priv-app/CallLogBackup"
rm -rf "/system/priv-app/GoogleFeedback"
rm -rf "/system/priv-app/ManagedProvisioning"
rm -rf "/system/priv-app/MusicFX"
rm -rf "/system/priv-app/UserDictionaryProvider"
rm -rf "/system/phh/huawei"
rm "/system/overlay/treble-overlay-asus*.apk"
rm "/system/overlay/treble-overlay-bq-jeice.apk"
rm "/system/overlay/treble-overlay-caf-ims.apk"
rm "/system/overlay/treble-overlay-devinputjack.apk"
rm "/system/overlay/treble-overlay-htc*.apk"
rm "/system/overlay/treble-overlay-huawei*.apk"
rm "/system/overlay/treble-overlay-lenovo*.apk"
rm "/system/overlay/treble-overlay-lg*.apk"
rm "/system/overlay/treble-overlay-moto*.apk"
rm "/system/overlay/treble-overlay-nokia*.apk"
rm "/system/overlay/treble-overlay-oneplus*.apk"
rm "/system/overlay/treble-overlay-razer*.apk"
rm "/system/overlay/treble-overlay-sharp*.apk"
rm "/system/overlay/treble-overlay-sony*.apk"
rm "/system/overlay/treble-overlay-xiaomi*.apk"
