su
pm disable com.android.internal.display.cutout.emulation.corner
pm disable com.android.internal.display.cutout.emulation.double
pm disable com.google.android.onetimeinitializer
pm disable com.android.htmlviewer
pm disable com.android.messaging
pm disable com.android.internal.display.cutout.emulation.tall
pm disable com.android.egg
pm disable com.google.android.setupwizard
pm disable com.android.gallery3d
pm disable com.android.calllogbackup
pm disable org.lineageos.jelly
pm disable com.android.inputmethod.latin
pm disable org.lineageos.eleven
pm disable com.google.android.feedback
pm disable org.lineageos.snap
pm disable com.android.managedprovisioning
pm disable com.android.dreams.phototable
pm disable com.android.wallpaper.livepicker
pm disable com.android.bookmarkprovider
pm disable com.android.email
pm disable com.android.providers.userdictionary
pm disable com.android.exchange
pm disable com.google.android.apps.restore
pm disable org.lineageos.overlay.accent.black
pm disable org.lineageos.overlay.accent.brown
pm disable org.lineageos.overlay.accent.green
pm disable org.lineageos.overlay.accent.orange
pm disable org.lineageos.overlay.accent.purple
pm disable org.lineageos.overlay.accent.yellow
pm disable org.lineageos.overlay.accent.blue
pm disable org.lineageos.overlay.accent.cyan
pm disable org.lineageos.overlay.accent.pink
pm disable org.lineageos.overlay.accent.red
